export const orders = [
    {
      orderNumber: '12345',
      dateTime: '2024-07-16 10:30 AM',
      status: 'New Orders',
      statusImage: '/images/ordermanagement/neworder.svg',
      customerName: 'John Doe',
      phoneNumber: +919961257014,
      paymentType:'UPI',
      itemsCount: 3,
      item:'Idiyappam',
      itemImage: '/images/dashboard/idiyappam.svg',
      price:200,
      quantity: 3,
      tableNumber: 5,
      amount: 5999
    },
    {
      orderNumber: '12346',
      dateTime: '2024-07-16 11:00 AM',
      status: 'On Cook',
      statusImage: '/images/ordermanagement/oncook.svg',
      customerName: 'Jane Smith',
       phoneNumber: +919968257014,
       paymentType:'UPI',
      itemsCount: 2,
      item:'Chappati',
      itemImage: '/images/dashboard/idiyappam.svg',
      price:20,
      quantity: 3,
      tableNumber: 7,
      amount: 4250
    },
    {
        orderNumber: '12347',
        dateTime: '2024-07-16 10:30 AM',
        status: 'New Orders',
        statusImage: '/images/ordermanagement/neworder.svg',
        customerName: 'John Doe',
         phoneNumber: +919961257614,
         paymentType:'Cash',
         item:"Porotta",
         itemImage: '/images/dashboard/idiyappam.svg',
         price:20,
         quantity: 3,
        itemsCount: 3,
        tableNumber: 5,
        amount: 5999
      },
      {
        orderNumber: '12348',
        dateTime: '2024-07-16 11:00 AM',
        status: 'Delivered',
        statusImage: '/images/ordermanagement/delivered.svg',
        customerName: 'Jane Smith',
       phoneNumber: +919991257014,
       paymentType:'Debit Card',
       item:'Idiyappam',
       itemImage: '/images/dashboard/idiyappam.svg',
       price:200,
       quantity: 3,
        itemsCount: 2,
        tableNumber: 7,
        amount: 4250
      },
      {
        orderNumber: '12349',
        dateTime: '2024-07-16 10:30 AM',
        status: 'Cancelled',
        statusImage: '/images/ordermanagement/cancelled.svg',
        customerName: 'John Doe',
         phoneNumber: +919961297014,
         paymentType:'Bank Transfer',
         item:'Idiyappam',
         itemImage: '/images/dashboard/idiyappam.svg',
         price:200,
         quantity: 3,
        itemsCount: 3,
        tableNumber: 5,
        amount: 5999
      },
      {
        orderNumber: '12350',
        dateTime: '2024-07-16 11:00 AM',
        status: 'Delivered',
        statusImage: '/images/ordermanagement/delivered.svg',
        customerName: 'Jane Smith',
         phoneNumber: +919961257010,
         paymentType:'Bank Transfer',
         item:'Idiyappam',
         itemImage: '/images/dashboard/idiyappam.svg',
         price:200,
         quantity: 3,
        itemsCount: 2,
        tableNumber: 7,
        amount: 4250
      },

  ];
  